spring:
  datasource:
    url: jdbc:postgresql://localhost/digital_banking_application
    username: postgres
    password: password
  jpa:
    show-sql : false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect